[build]
  command = "pnpm build"
  publish = "dist"

# Redirecciones para forzar trailingSlash: never en las ra√≠ces de locales
[[redirects]]
  from = "/es/"
  to = "/es"
  status = 301
  force = true

[[redirects]]
  from = "/en/"
  to = "/en"
  status = 301
  force = true
